name: Build app

on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
  pull_request:

jobs:
  build-app:
    uses: les-chauffagistes/deploy/.github/workflows/build.yml@develop
    with:
      service-name: heatboard
      build-target: runner
      build-args: |
        NEXT_PUBLIC_BASE_URL=https://heatboard.chauffagistes-btc.fr
        NEXT_PUBLIC_API_URL=https://chauffagistes-pool.fr:3000
        NEXT_PUBLIC_HISTORY_API_URL=https://history.chauffagistes-btc.fr
        NEXT_PUBLIC_BITCOIN_API_URL=https://bitcoin.chauffagistes-btc.fr
    secrets: inherit

  build-migrator:
    uses: les-chauffagistes/deploy/.github/workflows/build.yml@develop
    with:
      service-name: heatboard-migrator
      build-target: migrator
    secrets: inherit